const TEAM_DATA = 'TEAM_DATA'
const TEAM_CONTENT_DATA = 'TEAM_CONTENT_DATA'
const TEAM_REQ_DATA = 'TEAM_REQ_DATA'
const TEAM_URL = 'TEAM_URL'
const FINAL_DATA = 'FINAL_DATA'
const CAR_DATA = 'CAR_DATA'
const CAR_DELECT = 'CAR_DELECT'
const REL_CAR_DATA = 'REL_CAR_DATA'
const REPLAYING_PAGE = 'REPLAYING_PAGE'
const CONTROL_ITEM_NUM = 'CONTROL_ITEM_NUM'
const COUNT_ITEM_SUM = 'COUNT_ITEM_SUM'


export {
    TEAM_DATA,
    TEAM_CONTENT_DATA,
    TEAM_REQ_DATA,
    TEAM_URL,
    FINAL_DATA,
    CAR_DATA,
    CAR_DELECT,
    REL_CAR_DATA,
    REPLAYING_PAGE,
    CONTROL_ITEM_NUM,
    COUNT_ITEM_SUM
}